//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyclasesTest {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Myclases : global::System.Configuration.ApplicationSettingsBase {
        
        private static Myclases defaultInstance = ((Myclases)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Myclases())));
        
        public static Myclases Default {
            get {
                return defaultInstance;
            }
        }
    }
}
